### ISSUE TITLE
How set the template folder?

### ISSUE THREAD

**Issue by mamcx** [Dzoukr/Shaver#1]
I'm trying to load a include template but I get the error:

`Could not resolve template ~/templates/product.html`

I have a suave F# project, where the folders are:

```
Root
-- static (css, js, etc)
-- templates
---- base.html
---- products.html
---- product.html

```

Then I try in products.html:

```
<section class="row">
@foreach(var item in @Model.Products) {
    @Include("~/templates/product.html", item)
}
</section>
```

So I can render:

```
    <div class="thumbnail">
        <img src="http://placehold.it/320x220" alt="" />
        <div class="caption">
            <h4 class="pull-right">Silver, Black, Gold, Coffee, Blue</h4>
            <h4><a href="#">@Model.name</a>
            </h4>
            <p>@Model.description</p>
            <a class="btn btn-link" href="#" role="button">Ver</a>
            <a class="btn btn-primary" href="#" role="button">Link</a>
        </div>
    </div>
```

**Comment by Dzoukr** [comment]
Hi @mamcx,
did you set "Copy to output folder" on each template? Template must exist in output folder (mostly bin/Debug). Also `Include` method in template should be called with relative paths (please see example in tests  https://github.com/Dzoukr/Shaver/blob/master/tests/Shaver.Tests/razorInclude.html).

Please let me know.
